name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build app
        run: (./scripts/buildprod.sh)

      - name: Auuthenticate to GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}' 

      - name: Push docker image
        run: (gcloud builds submit --tag europe-central2-docker.pkg.dev/valid-climber-394813/notely-ar-repo/notely:latest .)

      - name: 'Deploy to Cloud Run'
        run: gcloud run deploy notely --image europe-central2-docker.pkg.dev/valid-climber-394813/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project valid-climber-394813 --max-instances=4